# Generated by Django 5.1.3 on 2024-12-02 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=64)),
                ("teacher", models.CharField(max_length=64)),
            ],
        ),
    ]
