# Generated by Django 5.1.3 on 2024-12-02 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="id",
            new_name="cid",
        ),
    ]
